// Command gen produces sessions.json, the golden data that pins the lakeFS
// browser session cookie format for the Rust implementation.
//
// Run it through Docker because Go is not installed on the development host:
//
//	docker run --rm -u $(id -u):$(id -g) -e GOCACHE=/tmp/gocache -e GOMODCACHE=/tmp/gomod \
//	  -e GOFLAGS=-mod=mod -v "$PWD/crates/lakefs-authn/fixtures:/out" -w /out golang:1.24 \
//	  sh -c 'go mod tidy && go run gen.go > sessions.json'
//
// Every case carries:
//   - gob_hex: the exact bytes of gob.Encode(map[interface{}]interface{}{"token": t})
//   - envelope: a securecookie envelope built at a pinned timestamp, which this
//     program then feeds back through gorilla's own Decode before emitting it
//   - store_cookie: the Set-Cookie value a real sessions.CookieStore produced
//
// The envelope and the store cookie are omitted for the very large tokens, where
// they would add hundreds of kilobytes and prove nothing the small cases do not.
package main

import (
	"bytes"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/gob"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"runtime"
	"strconv"
	"strings"

	"github.com/gorilla/securecookie"
	"github.com/gorilla/sessions"
)

const (
	cookieName = "internal_auth_session"
	hashKey    = "lakefs fixture shared secret"
	// 2026-01-01T00:00:00Z, so the envelopes never change between runs.
	pinnedTimestamp = int64(1767225600)
	// Above this length the envelope and the store cookie are left out.
	envelopeLimit = 1024
	// Longer tokens are written as a repeated character instead of a literal.
	literalLimit = 1024
)

// A realistic lakeFS login JWT: HS256 header, the claims lakeFS reads, a 32 byte MAC.
const realisticJWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9." +
	"eyJqdGkiOiI3ZTNkOTFhMi1kYTRkLTRkMGEtOTE0Zi1mMWQxYmI3YjRkYzEiLCJpc3MiOiJhdXRoIiwic3ViIjoi" +
	"YWxpY2VAZXhhbXBsZS5jb20iLCJhdWQiOiJsb2dpbiIsImlhdCI6MTc2NzIyNTYwMCwiZXhwIjoxNzY3ODMwNDAwfQ." +
	"Q2h3S1hQTk5xYnYzVzRhTXdiUFhkV2hFN2xjMmFwbHNLUnRqQmRVdEhJUQ"

type fixtureCase struct {
	Name string `json:"name"`
	// The token, either as a literal or as a repeated character.
	Token       string `json:"token,omitempty"`
	TokenRepeat string `json:"token_repeat,omitempty"`
	TokenLen    int    `json:"token_len"`
	GobHex      string `json:"gob_hex"`
	Envelope    string `json:"envelope,omitempty"`
	StoreCookie string `json:"store_cookie,omitempty"`
	StoreTS     int64  `json:"store_timestamp,omitempty"`
}

type fixture struct {
	Comment         string        `json:"comment"`
	GoVersion       string        `json:"go_version"`
	CookieName      string        `json:"cookie_name"`
	HashKey         string        `json:"hash_key"`
	PinnedTimestamp int64         `json:"pinned_timestamp"`
	MapTypeID       int64         `json:"map_type_id"`
	Cases           []fixtureCase `json:"cases"`
}

func main() {
	lengths := []int{0, 1, 5, 100, 127, 128, 129, 200, 255, 256, 257, 1000, 65535, 65536}
	out := fixture{
		Comment: "Generated by gen.go through docker run golang:1.24. " +
			"gob_hex is gob.Encode(map[interface{}]interface{}{\"token\": token}). " +
			"envelope is a securecookie envelope at pinned_timestamp, verified with gorilla Decode. " +
			"store_cookie comes from a real sessions.CookieStore. " +
			"Tokens longer than 1024 bytes are token_repeat repeated token_len times and carry no envelope.",
		GoVersion:       runtime.Version(),
		CookieName:      cookieName,
		HashKey:         hashKey,
		PinnedTimestamp: pinnedTimestamp,
	}

	for _, length := range lengths {
		out.Cases = append(out.Cases, build(fmt.Sprintf("len-%d", length), strings.Repeat("x", length)))
	}
	out.Cases = append(out.Cases, build("realistic-jwt", realisticJWT))
	out.MapTypeID = mapTypeID(encodeGob(""))

	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(out); err != nil {
		panic(err)
	}
}

func build(name, token string) fixtureCase {
	raw := encodeGob(token)
	entry := fixtureCase{
		Name:     name,
		TokenLen: len(token),
		GobHex:   hex.EncodeToString(raw),
	}
	if len(token) <= literalLimit {
		entry.Token = token
	} else {
		entry.TokenRepeat = token[:1]
	}
	if len(token) <= envelopeLimit {
		entry.Envelope = seal(cookieName, raw, pinnedTimestamp)
		verify(entry.Envelope, token)
		entry.StoreCookie = storeCookie(token)
		entry.StoreTS = timestampOf(entry.StoreCookie)
	}
	return entry
}

// encodeGob mirrors securecookie.GobEncoder on a gorilla session value map.
func encodeGob(token string) []byte {
	var buf bytes.Buffer
	values := map[interface{}]interface{}{"token": token}
	if err := gob.NewEncoder(&buf).Encode(values); err != nil {
		panic(err)
	}
	return buf.Bytes()
}

// seal reimplements securecookie.Encode so that the timestamp can be pinned.
// verify then proves the result is exactly what gorilla accepts.
func seal(name string, value []byte, timestamp int64) string {
	encoded := base64.URLEncoding.EncodeToString(value)
	signed := fmt.Sprintf("%s|%d|%s", name, timestamp, encoded)
	mac := hmac.New(sha256.New, []byte(hashKey))
	mac.Write([]byte(signed))
	payload := append([]byte(fmt.Sprintf("%d|%s|", timestamp, encoded)), mac.Sum(nil)...)
	return base64.URLEncoding.EncodeToString(payload)
}

func verify(envelope, token string) {
	codec := securecookie.New([]byte(hashKey), nil)
	// The pinned timestamp is in the past, so switch the age check off.
	codec.MaxAge(0)
	codec.MaxLength(0)
	decoded := map[interface{}]interface{}{}
	if err := codec.Decode(cookieName, envelope, &decoded); err != nil {
		panic(fmt.Sprintf("gorilla refused our envelope: %v", err))
	}
	if decoded["token"] != token {
		panic("gorilla decoded a different token")
	}
}

// storeCookie runs the real gorilla sessions path and returns the Set-Cookie value.
func storeCookie(token string) string {
	store := sessions.NewCookieStore([]byte(hashKey))
	for _, codec := range store.Codecs {
		if secure, ok := codec.(*securecookie.SecureCookie); ok {
			secure.MaxLength(0)
		}
	}
	request := httptest.NewRequest(http.MethodGet, "http://lakefs.example.com/", nil)
	recorder := httptest.NewRecorder()
	session, err := store.New(request, cookieName)
	if err != nil {
		panic(err)
	}
	session.Values["token"] = token
	if err := session.Save(request, recorder); err != nil {
		panic(err)
	}
	for _, cookie := range recorder.Result().Cookies() {
		if cookie.Name == cookieName {
			return cookie.Value
		}
	}
	panic("the session store set no cookie")
}

func timestampOf(envelope string) int64 {
	raw, err := base64.URLEncoding.DecodeString(envelope)
	if err != nil {
		panic(err)
	}
	parts := bytes.SplitN(raw, []byte("|"), 3)
	if len(parts) != 3 {
		panic("envelope has no three parts")
	}
	value, err := strconv.ParseInt(string(parts[0]), 10, 64)
	if err != nil {
		panic(err)
	}
	return value
}

// mapTypeID reads the type id out of the first message of a gob stream.
func mapTypeID(stream []byte) int64 {
	cursor := stream
	readUint := func() uint64 {
		first := cursor[0]
		cursor = cursor[1:]
		if first < 128 {
			return uint64(first)
		}
		count := int(256 - int(first))
		var value uint64
		for _, b := range cursor[:count] {
			value = value<<8 | uint64(b)
		}
		cursor = cursor[count:]
		return value
	}
	readUint() // message length
	raw := readUint()
	signed := int64(raw >> 1)
	if raw&1 == 1 {
		signed = ^signed
	}
	return -signed
}
