{{- if and (not .Values.sharedSecret.existingSecret) .Values.sharedSecret.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: lakefs-auth-shared-secret
  labels:
    {{- include "lakefs-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.sharedSecret.secretKey }}: {{ .Values.sharedSecret.value | quote }}
{{- end }}
{{- if and .Values.authz.enabled (not .Values.authz.database.existingSecret) .Values.authz.database.url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: lakefs-authz-database
  labels:
    {{- include "lakefs-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.authz.database.secretKey }}: {{ .Values.authz.database.url | quote }}
{{- end }}
{{- if and .Values.authn.enabled (not .Values.authn.oidc.clientSecret.existingSecret) .Values.authn.oidc.clientSecret.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: lakefs-authn-oidc
  labels:
    {{- include "lakefs-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.authn.oidc.clientSecret.secretKey }}: {{ .Values.authn.oidc.clientSecret.value | quote }}
{{- end }}
